image: ghcr.io/cirruslabs/flutter:stable

variables:
  # This enables the build to find the Keystore uploaded to "Secure Files"
  SECURE_FILES_DOWNLOAD_PATH: './.gitlab/secure_files/'
  FLUTTER_VERSION: "3.41.3" # Match your local environment stable version

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Downloading secure files..."
    # This line is the missing link - it pulls your .jks from the GitLab vault
    - curl -sL https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - echo "Compiling the code..."
    - flutter pub get
    - flutter build apk --release
    - echo "Compile complete."
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG # Only run build-job when a version tag (e.g. v2.5.0) is pushed

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests..."
    - flutter test
    - echo "Tests complete."
  rules:
    - if: $CI_COMMIT_TAG

lint-test-job:   # This job also runs in the test stage.
  stage: test    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Linting code..."
    - flutter analyze
    - echo "No lint issues found."
  rules:
    - if: $CI_COMMIT_TAG

deploy-job:      # This job runs in the deployment stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build-job
      artifacts: true
  environment: production
  script:
    - echo "Deploying application to GitLab Releases..."
    - echo "Application successfully deployed."
  release:
    name: "Release $CI_COMMIT_TAG"
    description: "Automated distribution build for version $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    assets:
      links:
        - name: "Rental Manager APK"
          url: "${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/build/app/outputs/flutter-apk/app-release.apk"
  rules:
    - if: $CI_COMMIT_TAG